images = ['./../myportfolio/static/icons/django.svg',
	'./../myportfolio/static/icons/flask.svg',
	'./../myportfolio/static/icons/javascript.svg',
	'./../myportfolio/static/icons/sql.svg',
	'./../myportfolio/static/icons/sql_developers.svg',
	'./../myportfolio/static/icons/sql.svg',
	'./../myportfolio/static/icons/sql.svg',
	'./../myportfolio/static/icons/sql_developers.svg',
	'./../myportfolio/static/icons/mongo_db.svg',
	'./../myportfolio/static/icons/css.svg',
	'./../myportfolio/static/icons/python.svg',
	'./../myportfolio/static/icons/word_press.svg',
	'./../myportfolio/static/icons/html.svg',
	]